### ISSUE TITLE
About Us page size is different on Safari vs Chrome

### ISSUE THREAD

**Issue by jennifermtan** [GoodGameRuler/unitrack_v3#10]
Safari:
<img width="1512" alt="Screenshot 2024-05-19 at 10 59 12 AM" src="https://github.com/GoodGameRuler/unitrack_v3/assets/63948459/cbe6cfdf-5a30-4a5a-ab5e-a2518924e7f5">
Chrome (zoomed in):
<img width="1512" alt="Screenshot 2024-05-19 at 10 59 00 AM" src="https://github.com/GoodGameRuler/unitrack_v3/assets/63948459/7e834e92-7df3-4a5d-8c6a-a1fadd5dead7">

**Comment by jennifermtan** [comment]
@GoodGameRuler I read somewhere Safari sometimes automatically sets to 125% zoom.

**Comment by jennifermtan** [comment]
@GoodGameRuler Check this out: https://www.npmjs.com/package/normalize.css?activeTab=versions

**Comment by GoodGameRuler** [comment]
@jennifermtan This is what reset.css does

**Comment by GoodGameRuler** [comment]
After doing some research it seems like Apple OS scales (Safari OSX, IOS, IpadOS all scale things down)
Try using this line in the html tag of reset.css. You can test this in the developer console, or put the line in.

-webkit-text-size-adjust: 100%;
