### ISSUE TITLE
Minor UI change: "Units" page search bar wrong colour

### ISSUE THREAD

**Issue by jennifermtan** [GoodGameRuler/unitrack_v3#24]
- [x] Search bar should be the same as the nav bar colour :) (#DD432B)
- [x] Change the outline colour from blue on focus (any suitable colour is fine)

Currently:
<img width="1037" alt="Screenshot 2024-05-28 at 7 24 08 PM" src="https://github.com/GoodGameRuler/unitrack_v3/assets/63948459/76f39430-93ab-4dd7-a46e-b3d2d3cf53db">
<img width="1029" alt="Screenshot 2024-05-29 at 10 44 25 AM" src="https://github.com/GoodGameRuler/unitrack_v3/assets/63948459/b9d56589-99f5-4741-ba09-c5c50fe0610f">

**Comment by GoodGameRuler** [comment]
@jesstn closed pr
