### ISSUE TITLE
Degree details form default input

### ISSUE THREAD

**Issue by jennifermtan** [GoodGameRuler/unitrack_v3#36]
- [ ] Default optional inputs to "NA" as shown below

<img width="972" alt="Screenshot 2024-05-29 at 11 55 36 AM" src="https://github.com/GoodGameRuler/unitrack_v3/assets/63948459/cce69a7e-d63f-44f2-9da0-87c817166ede">

**Comment by ketansahugit** [comment]
Hey, I will start working on this.
