### ISSUE TITLE
Minor UI change: Degree planner page semester heading

### ISSUE THREAD

**Issue by jennifermtan** [GoodGameRuler/unitrack_v3#37]
- [ ] Remove colour on hover as semester heading is not a button

Currently:
<img width="227" alt="Screenshot 2024-05-29 at 11 57 30 AM" src="https://github.com/GoodGameRuler/unitrack_v3/assets/63948459/bc9df912-0663-4996-9e53-a13d5d82758e">

Want:
<img width="228" alt="Screenshot 2024-05-29 at 11 58 46 AM" src="https://github.com/GoodGameRuler/unitrack_v3/assets/63948459/64b1993c-b397-4133-9065-918f49157305">

**Comment by harith-aaron** [comment]
Hi @jennifermtan  I am ready to work on it. Can you please assign me?

**Comment by TheAshutoshGupta** [comment]
it is fixed now, you can merge the PR after reviewing
![Screenshot 2024-05-29 134356](https://github.com/GoodGameRuler/unitrack_v3/assets/125827121/d97a0787-a315-441c-ae0b-c00cf729006b)

**Comment by jennifermtan** [comment]
> Hi @jennifermtan I am ready to work on it. Can you please assign me?

Done!
