### ISSUE TITLE
Minor UI Issue: grid auto doesn't work with single 1fr.

### ISSUE THREAD

**Issue by GoodGameRuler** [GoodGameRuler/unitrack_v3#38]
Expected behaviour is to, in the page contents div is two have two left and right margins that are equal in size. 

We used `grid-template-columns: auto 1fr auto` for this in `pageContentsWrapper`
this is not working as expected I believe this works more as expected.

`1fr auto 1fr`

Here are the behaviours, please look at console and grid lines.

Current
![image](https://github.com/GoodGameRuler/unitrack_v3/assets/85796687/d64c1811-3afa-4663-a484-5edce0f3d097)

Expected
![image](https://github.com/GoodGameRuler/unitrack_v3/assets/85796687/54afeb62-624c-4d3b-ad4d-c12c4d9062c0)

**Comment by MehekFatima** [comment]
#29 

I have addressed the changes as suggested. I've encountered an issue with the nav bar container where the icon gets hidden when hovered over. Before proceeding to address this issue, I wanted to check with you to see if it's okay to proceed.

Can I go ahead and work on resolving this issue with the nav bar container?

[screen-recorder-wed-may-29-2024-12-39-18.webm](https://github.com/GoodGameRuler/unitrack_v3/assets/128465778/5e456ae0-a8c0-49fa-bc74-75dcc39e599c)
