### ISSUE TITLE
Minor UI bug: White background on first letter of input

### ISSUE THREAD

**Issue by jennifermtan** [GoodGameRuler/unitrack_v3#54]
Remove white background on first letter of input as shown:
<img width="989" alt="Screenshot 2024-05-31 at 10 50 42 AM" src="https://github.com/GoodGameRuler/unitrack_v3/assets/63948459/e16465d2-60eb-4c65-8b91-6f6121948568">

**Comment by GoodGameRuler** [comment]
Yoo, are we working on filter already? That's pretty sick! However, @jennifermtan  why are you procrastinating #7?

**Comment by GoodGameRuler** [comment]
Also, I think this is browser dependant, but defo worth looking into. I get this on only Brave not Chrome or Firefox. If you type two keys at the same time it actually the first two chars.

**Comment by jennifermtan** [comment]
> Yoo, are we working on filter already? That's pretty sick! However, @jennifermtan why are you procrastinating #7?

I'll do that one after exams cuz I need to learn to do APIs, so working on PRs I'm more familiar with before exams haha

**Comment by jennifermtan** [comment]
> Also, I think this is browser dependent, but defo worth looking into. I get this on only Brave not Chrome or Firefox. If you type two keys at the same time it actually the first two chars.

Oh yeah I noticed that too but I fixed it anyways, just needed to remove the background :P
