### ISSUE TITLE
Minor UI issue: Degree planner width

### ISSUE THREAD

**Issue by jennifermtan** [GoodGameRuler/unitrack_v3#61]
Currently, the content is centered in the page as shown below:
<img width="1512" alt="Screenshot 2024-05-31 at 7 46 45 PM" src="https://github.com/GoodGameRuler/unitrack_v3/assets/63948459/f1e1f00b-2bf3-4570-9e79-67867a1242cc">

We want to increase the width of the degree planner to take the space of the content as shown in the prototype:
<img width="789" alt="Screenshot 2024-05-31 at 7 45 48 PM" src="https://github.com/GoodGameRuler/unitrack_v3/assets/63948459/85643753-abcb-44df-aa4a-db2a0b6efa15">

**Comment by vverma022** [comment]
I'd like to try and implement the solution. Could you specify what you need ?

**Comment by jennifermtan** [comment]
> I'd like to try and implement the solution. Could you specify what you need ?

Hi, please look at the prototype and the text above it: "We want to increase the width of the degree planner to take the space of the content as shown in the prototype"

**Comment by vverma022** [comment]
Alright,thank you for clarifying. Could you assign this issue to me please.

**Comment by GoodGameRuler** [comment]
Apologies this is a duplicate issue.

The bug originates from PR: #29.
We introduced issues #46 and #50 to address the problem.

The issue stems from two factors:
- The details form and degree planner are on the same page.
- The two pages require different margins.

Marking this issue as duplicate and closing. @vverma022 feel free to PR the #46 or #50 to be assigned. Unfortunately, we don't assign new contributors until a correct PR.
