### ISSUE TITLE
Fixing warning: use 'defaultValue' instead of 'selected'

### ISSUE THREAD

**Issue by jennifermtan** [GoodGameRuler/unitrack_v3#65]
React warning as follows:
Warning: Use the `defaultValue` or `value` props on \<select\> instead of setting `selected` on \<option\>

**Comment by GoodGameRuler** [comment]
Apparently you can't use '\<' without using \\\< (without using a backslash)

Image:
![image](https://github.com/GoodGameRuler/unitrack_v3/assets/85796687/c945da92-ccf3-4a00-9194-508a9ea28f38)
