### ISSUE TITLE
Bug fix: Dynamic allocation of Year/Sem for Planning Page

### ISSUE THREAD

**Issue by dillondesilva** [GoodGameRuler/unitrack_v3#69]
When creating a new plan from scratch, the year/semester displayed by default is incorrect and I'm not sure how to edit this. Perhaps this is a feature that is on the backlog to be implemented or I am using it incorrectly?

Would be nice to have this page pre-fill the values when degree planner is loaded

https://github.com/GoodGameRuler/unitrack_v3/assets/10183259/32ce3bca-87c4-42b7-a036-300cb1e808ad

**Comment by dillondesilva** [comment]
<img width="474" alt="Screenshot 2024-06-02 at 2 46 13 pm" src="https://github.com/GoodGameRuler/unitrack_v3/assets/10183259/37c07bc1-64c9-4568-aa0b-cdf488e8cdc2">

Looks like these are hardcoded in as well - this could be fixed by allowing the following props to the SemesterPlan component:

1. year : string
2. sem : boolean (True is Semester 1 and False is Semester 2)

A string could also work for props.sem

**Comment by jennifermtan** [comment]
Yep currently it is just the skeleton. I already made issues #26 and #62 for this, so I'll close this as duplicate :)
