### ISSUE TITLE
Add a new unit in degree plan functionality

### ISSUE THREAD

**Issue by jennifermtan** [GoodGameRuler/unitrack_v3#8]
Functionality will consist of:
- [ ] Add an empty unit when the add icon is clicked on for each row
- [ ] Ensure that it is horizontally scrollable if it exceeds the width of the row

Before adding on the first row:
<img width="777" alt="Screenshot 2024-05-28 at 7 44 56 PM" src="https://github.com/GoodGameRuler/unitrack_v3/assets/63948459/b90d9cf0-a714-4b49-86ed-69dd1f3cf5d1">

After adding on the first row:
<img width="620" alt="Screenshot 2024-05-28 at 7 45 54 PM" src="https://github.com/GoodGameRuler/unitrack_v3/assets/63948459/67e24f38-3f23-4b7c-901a-99fe124c14f4">

Scrollable in the first row:
<img width="826" alt="Screenshot 2024-05-28 at 7 47 52 PM" src="https://github.com/GoodGameRuler/unitrack_v3/assets/63948459/9c1414bb-0ecb-4577-9d5e-5537011c3679">

**Comment by GoodGameRuler** [comment]
@jennifermtan please update the issue requirements.

**Comment by jennifermtan** [comment]
> @jennifermtan please update the issue requirements.

Updated! I'll separate the functionality into different issues
